# Generated by Django 5.0.6 on 2024-07-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_contactt_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactt',
            new_name='Contact',
        ),
    ]
