# Generated by Django 5.0.6 on 2024-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_rename_contactt_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Purpose', models.TextField()),
                ('Phone', models.IntegerField()),
                ('Surgury', models.CharField(choices=[('car', 'Cardiology'), ('Dermatology and Cosmetology', 'Dermatology and Cosmetology'), ('General Surgery', 'General Surgery'), ('Neurology', 'Neurology'), ('Health Checkup Packages', 'Health Checkup Packages')], max_length=50)),
                ('Date', models.DateField(verbose_name='')),
                ('Time', models.CharField(choices=[('8 AM - 10 AM', '8 AM - 10 AM'), ('10 AM - 12 PM', '10 AM - 12 PM'), ('12 PM - 2 PM', '12 PM - 2 PM'), ('2 PM - 4 PM', '2 PM - 4 PM'), ('4 PM - 6 PM', '4 PM - 6 PM'), ('6 PM - 8 PM', '6 PM - 8 PM'), (' 8 PM - 10 PM', '8 PM - 10 PM')], max_length=50, verbose_name='')),
            ],
        ),
    ]
