# Generated by Django 5.0.6 on 2024-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Surgury',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('Derma', 'Dermatology and Cosmetology'), ('Gen', 'General Surgery'), ('Neuro', 'Neurology'), ('Health', 'Health Checkup Packages')], max_length=50),
        ),
    ]
