# Generated by Django 5.0.6 on 2024-07-15 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_alter_booking_surgury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Time',
            field=models.CharField(choices=[('8 AM - 10 AM', '8 AM - 10 AM'), ('10 AM - 12 PM', '10 AM - 12 PM'), ('12 PM - 2 PM', '12 PM - 2 PM'), ('2 PM - 4 PM', '2 PM - 4 PM'), ('4 PM - 6 PM', '4 PM - 6 PM'), ('6 PM - 8 PM', '6 PM - 8 PM'), (' 8 PM - 10 PM', '8 PM - 10 PM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
