# Generated by Django 5.0.6 on 2024-07-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_booking_user_alter_booking_date_alter_booking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
